### ISSUE TITLE
Add key config

### ISSUE THREAD

**Issue by LucaGabi** [syovchev/jump-brackets#1]
Great extention, but would help to add custom shortcuts,

**Comment by syovchev** [comment]
Hey, thanks for your feedback.
 
I think you should be able to override the default shortcuts in either your **Keyboard Shortcuts** or your **keybindings.json**.

If you go to File>Preferences>Keyboard Shortcuts you should find a list of all VS Code commands. Just search for one of jump-bracket's commands (i.e. 'jump-forward') and from there on you should easily be able to add your own shortcut.

Alternatively, you can `Ctrl+Shift+P`, search for 'Keyboard Shortcuts (JSON)' and directly override the commands, by simply adding:

> 
> {
>  "command":  _command you want to override (i. e. "jump-forward")_,
>  "key":  _your own shortcut (i.e. "ctrl+m")_
> }
> 

Let me know if this was what you were looking for and if so, I'll update the README to let others know how to do it as well.
